# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "117300033b063faa010de84e993ea241"
name = "Seeder"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
