export interface Address {
  address1: string;
  address2?: string;
  city: string;
  province: string;
  country: string;
  zip: string;
  phone?: string;
  default?: boolean;
}

// Address mapping by country code-province code
export const ADDRESS_MAPPING: Record<string, Address[]> = {
  "IN-MH": [
    {
      address1: "Amanora Gateway Towers, Hadapsar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411028",
    },
    {
      address1: "Trump Towers, Kalyani Nagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411006",
    },
    {
      address1: "Blue Ridge Township, Hinjawadi Phase 1",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411057",
    },
    {
      address1: "Magarpatta Cybercity, Magarpatta",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411028",
    },
    {
      address1: "EON Free Zone, Kharadi",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Panchshil Tech Park, Yerwada",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411006",
    },
    {
      address1: "Kumar Pacific Mall, Swargate",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411042",
    },
    {
      address1: "Seasons Mall, Magarpatta",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411028",
    },
    {
      address1: "Phoenix Marketcity, Viman Nagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Nyati Elysia, Kharadi",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Kunal Icon, Pimple Saudagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411027",
    },
    {
      address1: "Godrej Infinity, Keshav Nagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411036",
    },
    {
      address1: "Kolte Patil 24K Espada, Baner",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411045",
    },
    {
      address1: "Nanded City, Sinhagad Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411041",
    },
    {
      address1: "Rohan Mithila, Viman Nagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Marvel Zephyr, Kharadi",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Gera Imperium Alpha, Kharadi",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Pride World City, Charholi Budruk",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "412105",
    },
    {
      address1: "The Address, Baner-Pashan Link Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411021",
    },
    {
      address1: "Mont Vert Tropez, Wakad",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411057",
    },
    {
      address1: "Skyi Songbirds, Bhugaon",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "412115",
    },
    {
      address1: "Marvel Piazza, Viman Nagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Kohinoor World Towers, Pimpri",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411018",
    },
    {
      address1: "Westend Mall, Aundh",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411007",
    },
    {
      address1: "The Pavillion Mall, Senapati Bapat Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411016",
    },
    {
      address1: "Kumar Pinakin, Baner",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411045",
    },
    {
      address1: "Palash 2i, Wakad",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411057",
    },
    {
      address1: "Bramha Suncity, Wadgaonsheri",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Marvel Selva Ridge Estate, Bavdhan",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411021",
    },
    {
      address1: "Kumar Princetown Royal, Undri",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411060",
    },
    {
      address1: "Raheja Vistas Premiere, NIBM Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411048",
    },
    {
      address1: "Clover Highlands, Kondhwa",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411048",
    },
    {
      address1: "Godrej Hillside, Mahalunge",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411045",
    },
    {
      address1: "VTP Pegasus, Kharadi Annexe",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "412207",
    },
    {
      address1: "Ganga Legends County, Bavdhan",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411021",
    },
    {
      address1: "Kumar Picasso, Hadapsar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411028",
    },
    {
      address1: "Runwal Seagull, Handewadi Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411028",
    },
    {
      address1: "Forest Trails, Bhugaon",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "412115",
    },
    {
      address1: "Life Republic Township, Marunji",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411057",
    },
    {
      address1: "The Corinthians Club, NIBM Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411048",
    },
    {
      address1: "Raheja Sterling, NIBM Annexe",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411048",
    },
    {
      address1: "Prestige High Fields, Hinjawadi Phase 3",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411057",
    },
    {
      address1: "Shapoorji Pallonji Joyville, Hadapsar Annexe",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "412308",
    },
    {
      address1: "Kohinoor Sapphire, Tathawade",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411033",
    },
    {
      address1: "Vision Ace, Wakad",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411057",
    },
    {
      address1: "Mantra Insignia, Mundhwa",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411036",
    },
    {
      address1: "Kumar Prospera, Magarpatta Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411028",
    },
    {
      address1: "Godrej Rejuve, Keshav Nagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411036",
    },
    {
      address1: "Ravetkar Heights, Shivajinagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411005",
    },
    {
      address1: "The Capital, Baner",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411045",
    },
    {
      address1: "Pune Central Mall, East Street, Camp",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411001",
    },
    {
      address1: "Sassoon General Hospital, Civil Lines",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411001",
    },
    {
      address1: "Ruby Hall Clinic, Sassoon Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411001",
    },
    {
      address1: "JW Marriott Pune, Senapati Bapat Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411016",
    },
    {
      address1: "Taj Blue Diamond, Wanowrie",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411040",
    },
    {
      address1: "Grand Ashok, Koregaon Park",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411001",
    },
    {
      address1: "Camp Office Road, Pune Railway Station Area",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411001",
    },
    {
      address1: "Fergusson College Road, Deccan Gymkhana",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411004",
    },
    {
      address1: "Savitribai Phule Pune University, Ganeshkhind",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411007",
    },
    {
      address1: "Poona Club, Shivajinagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411005",
    },
    {
      address1: "Camp Hotel Aurora Towers, Bund Garden Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411001",
    },
    {
      address1: "Aundh Road, Baner Pashan Link",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411045",
    },
    {
      address1: "Deccan Gymkhana, JM Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411004",
    },
    {
      address1: "Kothrud, Mitra Mandal Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411038",
    },
    {
      address1: "Model Colony, Near JW Marriott",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411016",
    },
    {
      address1: "Sinhagad Road, Near College of Engineering",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411041",
    },
    {
      address1: "Koregaon Park, North Main Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411001",
    },
    {
      address1: "FC Road, Opposite Fergusson College",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411004",
    },
    {
      address1: "Pimple Nilakh, Pimple Saudagar Extension",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411027",
    },
    {
      address1: "Pimpri-Chinchwad Municipal Corporation Office, Pimpri",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411018",
    },
    {
      address1: "City One Mall, Pimpri",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411018",
    },
    {
      address1: "Xion Mall, Wakad",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411057",
    },
    {
      address1: "Aero Mall, Airport Road, Lohegaon",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411047",
    },
    {
      address1: "Elpro City Square Mall, Chinchwad",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411033",
    },
    {
      address1: "Chhatrapati Sambhaji Udyan, Bund Garden",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411001",
    },
    {
      address1: "Sawarkar Nagar, Shivaji Nagar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411005",
    },
    {
      address1: "Magarpatta City Centre, Hadapsar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411028",
    },
    {
      address1: "Amanora Mall, Hadapsar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411028",
    },
    {
      address1: "Clover Center, Camp Market",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411001",
    },
    {
      address1: "DG Pavilion, Senapati Bapat Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411016",
    },
    {
      address1: "Kalyani Nagar, Near Pune Airport Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411006",
    },
    {
      address1: "Yerawada Prison Road, Yerawada",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411006",
    },
    {
      address1: "NIBM Road, Kondhwa",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411048",
    },
    {
      address1: "Undri, Near Kunal Icon Circle",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411060",
    },
    {
      address1: "Kharadi Bypass Road, Near Nyati Elysia",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Hadapsar Industrial Estate, Hadapsar",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411028",
    },
    {
      address1: "Wadgaonsheri, Near Kharadi Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Narhe, Narhe Phata",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411041",
    },
    {
      address1: "Kondhwa Budruk, Near Kalyani Nagar Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411048",
    },
    {
      address1: "Katraj, Near Katraj Lake",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411046",
    },
    {
      address1: "Baner Road, Near Balewadi High Street",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411045",
    },
    {
      address1: "Bhosari MIDC, Near Pimpri-Chinchwad",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411039",
    },
    {
      address1: "Chandan Nagar, Nagar Road",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
    {
      address1: "Mundhwa, Near Oxford Golf Course",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411036",
    },
    {
      address1: "Kharadi Tech Park Road, Near EON Free Zone",
      city: "Pune",
      province: "Maharashtra",
      country: "India",
      zip: "411014",
    },
  ],
  "US-CA": [
    {
      address1: "1 Infinite Loop",
      city: "Cupertino",
      province: "California",
      country: "USA",
      zip: "95014",
    },
    {
      address1: "1600 Amphitheatre Parkway",
      city: "Mountain View",
      province: "California",
      country: "USA",
      zip: "94043",
    },
    {
      address1: "1 Hacker Way",
      city: "Menlo Park",
      province: "California",
      country: "USA",
      zip: "94025",
    },
    {
      address1: "345 Spear Street",
      city: "San Francisco",
      province: "California",
      country: "USA",
      zip: "94105",
    },
    {
      address1: "405 Howard Street",
      city: "San Francisco",
      province: "California",
      country: "USA",
      zip: "94105",
    },
    {
      address1: "1355 Market Street",
      city: "San Francisco",
      province: "California",
      country: "USA",
      zip: "94103",
    },
    {
      address1: "500 Terry A Francois Blvd",
      city: "San Francisco",
      province: "California",
      country: "USA",
      zip: "94158",
    },
    {
      address1: "800 W California Ave",
      city: "Sunnyvale",
      province: "California",
      country: "USA",
      zip: "94086",
    },
    {
      address1: "7000 Marina Blvd",
      city: "Brisbane",
      province: "California",
      country: "USA",
      zip: "94005",
    },
    {
      address1: "1200 Getty Center Dr",
      city: "Los Angeles",
      province: "California",
      country: "USA",
      zip: "90049",
    },
    {
      address1: "111 S Grand Ave",
      city: "Los Angeles",
      province: "California",
      country: "USA",
      zip: "90012",
    },
    {
      address1: "2211 North First Street",
      city: "San Jose",
      province: "California",
      country: "USA",
      zip: "95131",
    },
    {
      address1: "3333 Coyote Hill Rd",
      city: "Palo Alto",
      province: "California",
      country: "USA",
      zip: "94304",
    },
    {
      address1: "100 Winchester Circle",
      city: "Los Gatos",
      province: "California",
      country: "USA",
      zip: "95032",
    },
    {
      address1: "275 Shoreline Dr",
      city: "Redwood City",
      province: "California",
      country: "USA",
      zip: "94065",
    },
    {
      address1: "950 Elm Ave",
      city: "San Bruno",
      province: "California",
      country: "USA",
      zip: "94066",
    },
    {
      address1: "3450 Hillview Ave",
      city: "Palo Alto",
      province: "California",
      country: "USA",
      zip: "94304",
    },
    {
      address1: "500 Oracle Parkway",
      city: "Redwood Shores",
      province: "California",
      country: "USA",
      zip: "94065",
    },
    {
      address1: "600 Montgomery Street",
      city: "San Francisco",
      province: "California",
      country: "USA",
      zip: "94111",
    },
    {
      address1: "160 Spear Street",
      city: "San Francisco",
      province: "California",
      country: "USA",
      zip: "94105",
    },
  ],
};

export function getAddressesForLocation(
  countryCode: string,
  provinceCode?: string
): Address[] {
  const key = provinceCode ? `${countryCode}-${provinceCode}` : countryCode;
  return ADDRESS_MAPPING[key] || [];
}

export function getRandomAddresses(
  count: number,
  countryCode: string,
  provinceCode?: string
): Address[] {
  const addresses = getAddressesForLocation(countryCode, provinceCode);

  if (addresses.length === 0) {
    return [];
  }

  if (count > addresses.length) {
    count = addresses.length;
  }

  if (count > 20) {
    count = 20;
  }

  // Shuffle the addresses and take the first 'count' items
  const shuffled = [...addresses].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
